version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5004:5000
    environment:
      - DB_NAME=ticker_data_docker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_HOST=host.docker.internal
